# MongoDB Node 2 Configuration
# Replica Set: rs0 | Port: 27018

storage:
  dbPath: C:\data\rs0-1

systemLog:
  destination: file
  path: C:\data\rs0-1\mongod.log
  logAppend: true

net:
  port: 27018
  bindIp: 127.0.0.1

replication:
  replSetName: "rs0"
