# MongoDB Node 1 Configuration
# Replica Set: rs0 | Port: 27020

storage:
  dbPath: C:\data\rs0-0

systemLog:
  destination: file
  path: C:\data\rs0-0\mongod.log
  logAppend: true

net:
  port: 27020
  bindIp: 127.0.0.1

replication:
  replSetName: "rs0"
